### ISSUE TITLE
Wrong link in readme for docker desktop

### ISSUE THREAD

**Issue by chrizmc** [COVESA/cdsp#41]
**[Docker EE/Docker Desktop](https://github.com/chrizmc/cdsp/blob/main/docker)** is the commercial edition that provides a GUI and commercial support.

Seems to be wring link as it is not linked to docker desktop sw but to same readme

**Comment by slawr** [comment]
Thanks for the catch. I thought I had tested all the links but plainly not. I'll fix it.

**Comment by chrizmc** [comment]
https://github.com/COVESA/cdsp/pull/45/files

**Comment by slawr** [comment]
Reopened. Fix has been posted in PR, but not yet merged and checked.

**Comment by slawr** [comment]
Assigning to me for merge and check

**Comment by chrizmc** [comment]
https://github.com/COVESA/cdsp/pull/46

(This is new PR for this issue)
