### ISSUE TITLE
Add basic description of our "Hello World" Knowledge Layer use case and outlook for more valuable use cases

### ISSUE THREAD

**Issue by chrizmc** [COVESA/cdsp#58]
The Hello World use case (defined by @claireqiu some time ago) for the knowledge layer has not yet been publicly documented, but the current contributions are already driven by this Use Case. With this issue, a basic description of the use case should be published in the readme in the github even before the use case is finalized in order to create transparency for the public.
The readme should also contain a note indicating that after completion of the Hello World use case, a even more valuable use case should be defined that uses further aspects of a data-centric architecture such as the use of data from different data domains (e.g. not only VSS but also data about passengers or the environment, which requires a sync mechanism in the information layer). (fyi @slawr )

**Comment by slawr** [comment]
@chrizmc should the status of this ticket be "in progress" on the Kanban board? If so, can you update please.
