### ISSUE TITLE
task: Investigate the state of upstream MongoDB Realm Docker support 

### ISSUE THREAD

**Issue by slawr** [COVESA/cdsp#7]
Investigate the state of upstream MongoDB Realm Docker support to understand what could be used in CDSP Docker deployment

Task breakdown:

- [ ]  Summarise state of upstream Realm Docker support. Is it official? Where to find? Support?
- [ ]     Do sanity test to check that it works and record the results.

**Comment by 93arnaldo** [comment]
Realm wouldn't operate as a standalone service where it would need a Docker to be containerized. Instead, it will be directly integrated into the application, as an SDK. [Here](https://www.mongodb.com/docs/realm/introduction/#get-started-with-realm) a link to the SDKs supported. 
In a nutshell, the Docker container will be the one used for the application. 
Say we want a Node.js app in Docker, when building the Docker we would simply need to have a `npm install realm` and that would make Realm available for the Node.js application. 
Hope that helps! 

On the other hand, if what we want is to run MongoDB in Docker, there are two options:

- MongoDB community Docker image available [here](https://hub.docker.com/r/mongodb/mongodb-community-server)
- MongoDB enterprise Docker image available [here](https://hub.docker.com/r/mongodb/mongodb-enterprise-server)

**Comment by slawr** [comment]
Yes, from what you said in the last meeting this ticket could be closed and a follow on created to consider how to integrate Realm given its application DB architecture. Lets discuss this afternoon.

**Comment by slawr** [comment]
Closing issue. Superseded by discussion in the group. Realm does not have a standalone image. Work taking place in #15
